name: chainsafe-label-pr
on:
  - pull_request_target
jobs:
  Chainsafe-Label-PR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.TOKEN }}"
