name: chainsafe-ci
on: [pull_request]
jobs:
  Chainsafe-CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install app/
      - run: cd app/ && npm test
